### PR TITLE
Removing myself (and other dead souls)

### PR DESCRIPTION
**Pull request by kraklin**
👋

### CODE REVIEW

**Comment by Janiczek** [comment]
@kraklin Can you please add @nitrajka to the CODEOWNERS while you're at it?

**Comment by annaghi** [comment]
@kraklin Living in Nirvana in one life :smile:

**Comment by jhrcek** [comment]
Thanks! But now I'm curious as to why you're removing yourself :question: :smile:

**Comment by kraklin** [comment]
@jhrcek take your guess and the first one is probably the correct one :)

**Review by Janiczek — APPROVED** [review]
:+1:

**Pull request merged**
